# Generated by Django 3.0.5 on 2020-05-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída'), ('Estorno Entrada', 'Estorno Entrada'), ('Estorno Saída', 'Estorno Saída')], max_length=15)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade em estoque')),
                ('dt_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.Produto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.TipoMovimentacao', verbose_name='Tipo de Movimentação')),
            ],
        ),
    ]
