# Generated by Django 3.0.5 on 2020-05-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
