# Generated by Django 3.0.5 on 2020-05-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200503_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='qtd_estoque',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
    ]
