# Generated by Django 3.0.5 on 2020-05-04 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_article_qtd_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='date_compra',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Compra'),
            preserve_default=False,
        ),
    ]
