# Generated by Django 3.0.5 on 2020-05-04 02:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_section_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag (Palavras Chaves)', 'verbose_name_plural': 'Tags (Palavras Chaves)'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Chamada'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('article', smart_selects.db_fields.ChainedForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Article', verbose_name='Artigo')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.Menu', verbose_name='Pai')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Section', verbose_name='Seção')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
