# Generated by Django 3.0.5 on 2020-05-06 00:41

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200503_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('qtd_estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='article',
            name='qtd_estoque',
        ),
        migrations.AlterField(
            model_name='menu',
            name='article',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='section', chained_model_field='section', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Article', verbose_name='Artigo'),
        ),
        migrations.AddField(
            model_name='article',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
    ]
