# Generated by Django 3.0.5 on 2020-05-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200505_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publicated',
            field=models.BooleanField(default=False),
        ),
    ]
