# Generated by Django 3.0.5 on 2020-05-06 01:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_article_publicated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='O conteúdo pré-inscrito foi baseado no produto selecionado.', null=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Chamada'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publicated',
            field=models.BooleanField(default=False, help_text='Marque a caixa acima se quiser publicar este artigo.', verbose_name='Publicado'),
        ),
    ]
