# Generated by Django 3.0.5 on 2020-05-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200505_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dt_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação'),
        ),
    ]
